version: '3.8'

services:
  terraform-gcp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./terraform:/app/terraform
      - ${GOOGLE_APPLICATION_CREDENTIALS:-~/.config/gcloud/application_default_credentials.json}:/root/.config/gcloud/application_default_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - TF_IN_AUTOMATION=true
    healthcheck:
      test: ["CMD", "gcloud", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped